# Generated by Django 4.1.5 on 2023-01-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='без имени', max_length=200, verbose_name='Имя пользователя'),
        ),
    ]
