# Generated by Django 4.1.5 on 2023-01-17 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(upload_to='userfiles/', verbose_name='python-файл')),
                ('file_status', models.CharField(choices=[('new', 'new'), ('reload', 'reload'), ('in_work', 'in_work'), ('verified', 'verified')], default='new', max_length=8)),
                ('author', models.ForeignKey(help_text='Выберите автора объявления', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
        ),
    ]
