# Generated by Django 4.1.5 on 2023-01-22 12:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_task_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='log_file',
            field=models.FileField(default='settings.MEDIA_ROOT/file_logs/none', storage=django.core.files.storage.FileSystemStorage(location='E:\\djangoSkyenkins\\media'), upload_to='file_logs/', verbose_name='log-файл'),
        ),
    ]
