# Generated by Django 4.1.5 on 2023-01-22 12:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_task_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='log_file',
            field=models.FileField(default='E:\\djangoSkyenkins\\media/file_logs/none', storage=django.core.files.storage.FileSystemStorage(location='E:\\djangoSkyenkins\\media'), upload_to='file_logs/', verbose_name='log-файл'),
        ),
    ]
