# Generated by Django 4.1.5 on 2023-01-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_task_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='log_file',
            field=models.FileField(default='file_logs/none', upload_to='file_logs/', verbose_name='log-файл'),
        ),
    ]
