# Generated by Django 4.1.5 on 2023-01-24 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_user_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='user_file',
            field=models.FileField(upload_to='userfiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='Python-файл'),
        ),
    ]
